const pokemonTypes = {
  GET_POKEMONS_REQUEST: 'GET_POKEMONS_REQUEST',
  GET_POKEMONS_REQUEST_TAKE:'GET_POKEMONS_REQUEST_TAKE',
  GET_POKEMONS_REQUEST_TAKE_EVERY: 'GET_POKEMONS_REQUEST_TAKE_EVERY',
  GET_POKEMONS_REQUEST_TAKE_LATEST: 'GET_POKEMONS_REQUEST_TAKE_LATEST',
  GET_POKEMONS_REQUEST_TAKE_LEADING: 'GET_POKEMONS_REQUEST_TAKE_LEADING',
  GET_POKEMONS_REQUEST_RACE: 'GET_POKEMONS_REQUEST_RACE',
  GET_POKEMONS_REQUEST_ALL: 'GET_POKEMONS_REQUEST_ALL',
  GET_POKEMONS_SUCCESS: 'GET_POKEMONS_SUCCESS',
  GET_POKEMONS_ERROR: 'GET_POKEMONS_ERROR',
  CLEAN_POKEMONS: 'CLEAN_POKEMONS',


  GET_POKEMON_REQUEST: 'GET_POKEMON_REQUEST',
  GET_POKEMON_STOP: 'GET_POKEMON_STOP',
  GET_POKEMON_SUCCESS: 'GET_POKEMON_SUCCESS',
  GET_POKEMON_ERROR: 'GET_POKEMON_ERROR'

};

export default pokemonTypes;