const pokemonTypes = {
  GET_POKEMONS_REQUEST: 'GET_POKEMONS_REQUEST',
  GET_POKEMONS_SUCCESS: 'GET_POKEMONS_SUCCESS',
  GET_POKEMONS_ERROR: 'GET_POKEMONS_ERROR',

  GET_POKEMON_REQUEST: 'GET_POKEMON_REQUEST',
  GET_POKEMON_STOP: 'GET_POKEMON_STOP',
  GET_POKEMON_SUCCESS: 'GET_POKEMON_SUCCESS',
  GET_POKEMON_ERROR: 'GET_POKEMON_ERROR'
};

export default pokemonTypes;